# Generated by Django 5.2.17 on 2026-09-21 11:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(default="Untitled creation", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("prompt", models.TextField(max_length=2000)),
                ("image_key", models.CharField(max_length=300)),
                ("image_name", models.CharField(max_length=150)),
                ("image_width", models.PositiveIntegerField()),
                ("image_height", models.PositiveIntegerField()),
                ("video_key", models.CharField(blank=True, max_length=300)),
                ("video_mime", models.CharField(default="video/mp4", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("submitting", "Sending to renderer"),
                            ("running", "Generating"),
                            ("completed", "Ready"),
                            ("failed", "Failed"),
                            ("unknown", "Needs attention"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("comfy_id", models.CharField(blank=True, max_length=100)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generations",
                        to="studio.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="studio_gene_status_a26dee_idx"
                    )
                ],
            },
        ),
    ]
